### ISSUE TITLE
Several issue about model and backbone

### ISSUE THREAD

**Issue by RonaldYuren** [xinzhuma/monodle#22]
Traceback (most recent call last):
  File "../../tools/train_val.py", line 82, in <module>
    main()
  File "../../tools/train_val.py", line 42, in main
    model = build_model(cfg['model'])
  File "/home/gene/YuRen/monodle/lib/helpers/model_helper.py", line 6, in build_model
    return CenterNet3D(backbone=cfg['backbone'], neck=cfg['neck'], num_class=cfg['num_class'])
  File "/home/gene/YuRen/monodle/lib/models/centernet3d.py", line 27, in __init__
    self.backbone = getattr(dla, backbone)(pretrained=True, return_levels=True)
  File "/home/gene/YuRen/monodle/lib/backbones/dla.py", line 318, in dla34
    model.load_pretrained_model(data='imagenet', name='dla34', hash='ba72cf86')
  File "/home/gene/YuRen/monodle/lib/backbones/dla.py", line 304, in load_pretrained_model
    model_weights = model_zoo.load_url(model_url)
  File "/home/gene/miniconda3/envs/monodle/lib/python3.6/site-packages/torch/hub.py", line 418, in load_state_dict_from_url
    os.makedirs(model_dir)
  File "/home/gene/miniconda3/envs/monodle/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/home/gene/miniconda3/envs/monodle/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/gene/.cache/torch'

I am new to this field.
Should I download the backbone and the model  first to run the training ?   if yes, where is the backbone or the model ?
If not, what is the possible error ?

**Comment by RonaldYuren** [comment]
I have resolve the problem with upload the dla34.pth by hand.
But I want to take an picture from testset , and use that picture to visualize the outcome of the model.
I am confused about how to input the picture into this model.

**Comment by xinzhuma** [comment]
it seems something is wrong when the code automatically downloads and saves the pre-trained backbone weight.  make sure you have the read and write permissions for corresponding directions.

**Comment by xinzhuma** [comment]
the results will be saved in the '#root/experiments/your experiment/output/data'.  you can get the detection results and visualize them in the corresponding images. here is the example code for visualization: https://github.com/xinzhuma/patchnet/blob/master/tools/visualization.py
